# Flipkart Order Issue Resolution Dashboard  
## Python Developer Workplace Handover Capstone

You have joined the simulated Flipkart customer support operations engineering team as a **Python Developer**.

This is not a normal classroom assignment. You are taking ownership of an unfinished internal Colab product after the previous developer resigned. The Product Manager has already written a PRD, the Engineering Manager has handed over the broken codebase, and only one core feature is currently working.

**Your final deliverable:** one completed Google Colab notebook with all outputs visible.

## Handover Context

You are expected to behave like the Python Developer who has inherited this notebook.

The business team needs an internal tool that can:

- Load synthetic order operations datasets.
- Detect delayed and risky orders.
- Identify refund-priority cases.
- Summarize customer complaints and support tickets.
- Produce a final issue-resolution report.
- Provide a simple Colab-based search/filter experience.
- Document implementation decisions, assumptions, PRD mapping, and AI prompt usage.

The previous developer completed only the basic `orders.csv` loading feature. The rest of the notebook contains broken code, incomplete logic, fragile assumptions, and TODO sections.

## Documents You Must Read Before Coding

Before completing the notebook, read the documents provided in the student resource folder:

1. `Meeting_Transcript_Flipkart_Order_Issue_Resolution_Dashboard.docx`
2. `PRD_Flipkart_Order_Issue_Resolution_Dashboard.docx`
3. `prd_completion_checklist.csv`
4. `student_readme.md`

Use the PRD as the product source of truth. Use the meeting transcript as the handover context.

## Dataset Upload Instructions for Google Colab

Upload the dataset ZIP file named:

`flipkart_order_issue_resolution_dataset.zip`

The code below extracts the ZIP and creates the dataset path.

The ZIP contains synthetic training data only. It does not contain real Flipkart data.

In [1]:
from pathlib import Path
import zipfile
import os

DATASET_ZIP = "flipkart_order_issue_resolution_dataset.zip"
EXPECTED_FOLDER = "flipkart_order_issue_resolution_dataset"

# In Google Colab, upload the dataset ZIP if it is not already present.
try:
    from google.colab import files
    if not Path(DATASET_ZIP).exists():
        print("Upload the dataset ZIP file:", DATASET_ZIP)
        uploaded = files.upload()
except Exception:
    # Non-Colab execution fallback.
    pass

if not Path(DATASET_ZIP).exists():
    raise FileNotFoundError(
        f"{DATASET_ZIP} not found. Upload it to the current Colab session before running this notebook."
    )

if not Path(EXPECTED_FOLDER).exists():
    with zipfile.ZipFile(DATASET_ZIP, "r") as zip_ref:
        zip_ref.extractall(".")

DATA_DIR = Path(EXPECTED_FOLDER)
if not (DATA_DIR / "orders.csv").exists():
    # Defensive fallback in case the ZIP structure changes.
    candidates = list(Path(".").rglob("orders.csv"))
    if not candidates:
        raise FileNotFoundError("orders.csv was not found after extracting the dataset ZIP.")
    DATA_DIR = candidates[0].parent

print("Dataset folder ready:", DATA_DIR.resolve())
print("Available files:")
for file in sorted(DATA_DIR.iterdir()):
    print(" -", file.name)

Upload the dataset ZIP file: flipkart_order_issue_resolution_dataset.zip

Saving flipkart_order_issue_resolution_dataset.zip to flipkart_order_issue_resolution_dataset.zip
Dataset folder ready: /content/flipkart_order_issue_resolution_dataset
Available files:
 - customer_complaints.json
 - customers.csv
 - orders.csv
 - refunds.xlsx
 - sellers.csv
 - status_notes.txt
 - support_tickets.csv

## Section 1: Imports, Configuration, and Developer Environment Check

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`

**How to approach:**
- Review existing imports.
- Add missing imports only when required.
- Confirm the notebook is running in a Colab-compatible Python environment.

**Expected output format:**
- Printed project name.
- Confirmation that Python/Pandas environment started.

**Hint:**
- Keep imports centralized so later sections are easier to debug.

In [3]:
import pandas as pd
import numpy as np
import json
from pathlib import Path
from datetime import datetime

PROJECT_NAME = "Flipkart Order Issue Resolution Dashboard"
TICKET_SLA_HOURS = 48      # isse slow ticket = SLA breach
REFUND_SLA_DAYS = 7        # isse purana refund = SLA breach

print(PROJECT_NAME)
print("Python/Pandas environment started. pandas version:", pd.__version__)

Flipkart Order Issue Resolution Dashboard
Python/Pandas environment started. pandas version: 2.2.3

## Section 2: Load Main Orders Dataset — Working Core Feature

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`

**How to approach:**
- Use the dataset path created during ZIP extraction.
- Load the main order table with Pandas.
- Display the row count and sample rows.

**Expected output format:**
- Printed row count.
- DataFrame preview with order columns.

**Hint:**
- This is the only feature that the previous developer completed reliably.

In [4]:
# SECTION 2 — Working core feature from the previous developer
# This is the only section that is known to work correctly.

orders_df = pd.read_csv(DATA_DIR / "orders.csv")

print("Orders loaded successfully.")
print("Row count:", len(orders_df))
display(orders_df.head())

Orders loaded successfully.
Row count: 5000

     order_id customer_id seller_id  order_date order_time promised_delivery_date actual_delivery_date  order_amount    payment_method order_status     delay_reason delivery_city device_type seller_category
0  ORD0000001  CUST000771  SELL0475  2026-05-30   10:51:46             2026-06-03           2026-06-03      57056.16  Cash on Delivery    Delivered              NaN         Delhi         iOS     Electronics
1  ORD0000002  CUST000122  SELL0035  2026-05-05   15:59:45             2026-05-08           2026-05-07      25038.34               UPI    Delivered              NaN      Gurugram         iOS         Grocery
2  ORD0000003  CUST000784  SELL0785  2026-05-11   11:48:01             2026-05-15                  NaN      29439.12               UPI   processing  Warehouse Delay       Lucknow     Android         Grocery
3  ORD0000004  CUST000288  SELL0211  2026-05-23   03:12:27             2026-05-27           2026-05-25      60697.51              Card    Delivered              NaN        Indore     Android          Beauty
4  ORD0000005  CUST001168  SELL0981  2026-06-14   00:30:13             2026-06-19                  NaN      56251.50               UPI    Cancelled   Payment Failed        Nagpur  Mobile Web          Beauty

## Section 3: Basic Order Summary

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`

**How to approach:**
- Summarize rows, columns, unique orders, customers, sellers.
- Find duplicate order IDs and missing values.
- Create a status summary.

**Expected output format:**
- One summary table.
- One order status frequency table.

**Hint:**
- The raw column is `order_status`, not `status`.

In [5]:
# SECTION 3 — Basic order summary
# The previous developer started this, but it is incomplete.
# TODO: Expand this into a useful summary for operations.
order_summary = pd.DataFrame({
    "metric": ["Rows", "Columns", "Unique order IDs", "Duplicate order IDs", "Customers", "Sellers", "Missing values"],
    "value": [len(orders_df), orders_df.shape[1], orders_df["order_id"].nunique(), orders_df["order_id"].duplicated().sum(),
              orders_df["customer_id"].nunique(), orders_df["seller_id"].nunique(), orders_df.isna().sum().sum()]})
display(order_summary)

print("Missing values by column:")
print(orders_df.isna().sum()[lambda s: s > 0])

status_summary = orders_df["order_status"].str.strip().str.replace("_", " ").str.title().value_counts().reset_index()
status_summary.columns = ["order_status", "count"]
display(status_summary)
# TODO: Add unique order count, duplicate order count, missing values,
# customer count, seller count, and order status summary.

                metric  value
0                 Rows   5000
1              Columns     14
2     Unique order IDs   4984
3  Duplicate order IDs     16
4            Customers   1227
5              Sellers   1017
6       Missing values   3783

Missing values by column:
promised_delivery_date       4
actual_delivery_date      1012
order_amount                13
delay_reason              2754
dtype: int64

     order_status  count
0       Delivered   2754
1         Delayed    597
2       Cancelled    488
3      Processing    438
4        Returned    378
5  Refund Pending    259
6            Lost     86

## Section 4: Debug Fix Log Setup

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `Notebook codebase`

**How to approach:**
- Create a structured debug log.
- Add a helper function to append fixes.
- Update the log after each major repaired section.

**Expected output format:**
- DataFrame with section, issue_found, fix_applied, validation_output.

**Hint:**
- Think like a developer documenting a handover fix, not like a student writing comments.

In [6]:
# SECTION 4 — Debug fix log setup
# BROKEN/TODO: This should become a log you update as you repair the codebase.

debug_log = []

def log_fix(section, issue, fix, validation):
    debug_log.append({"section": section, "issue_found": issue, "fix_applied": fix, "validation_output": str(validation)})

log_fix("Section 3", "Code used non-existent column 'status'", "Used order_status and added full summary", f"{len(status_summary)} status labels")
pd.DataFrame(debug_log)

# TODO: Add a function that accepts section, issue, fix, and validation evidence.
# Example expected fields:
# section, issue_found, fix_applied, validation_output

     section                             issue_found                               fix_applied validation_output
0  Section 3  Code used non-existent column 'status'  Used order_status and added full summary   7 status labels

## Section 5: Multi-File DataLoader

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`
- `customers.csv`
- `sellers.csv`
- `refunds.xlsx`
- `customer_complaints.json`
- `support_tickets.csv`
- `status_notes.txt`

**How to approach:**
- Create a reusable loader class.
- Use the correct method for each file format.
- Add basic exception handling.

**Expected output format:**
- Summary table with dataset name, rows, and columns/text lines.

**Hint:**
- The refunds file is Excel, complaints are JSON, and notes are TXT.

In [7]:
# SECTION 5 — Multi-file DataLoader
# BROKEN: File names and loading methods are incomplete.

class FlipkartIssueDataLoader:
    def __init__(self, folder_path):
        self.folder = Path(folder_path)

    def load_all(self):
        data = {}
        try:
            data["orders"] = pd.read_csv(self.folder / "orders.csv")
            data["customers"] = pd.read_csv(self.folder / "customers.csv")
            data["sellers"] = pd.read_csv(self.folder / "sellers.csv")
            data["refunds"] = pd.read_excel(self.folder / "refunds.xlsx")
            data["complaints"] = pd.read_json(self.folder / "customer_complaints.json")
            data["tickets"] = pd.read_csv(self.folder / "support_tickets.csv")
            data["notes"] = (self.folder / "status_notes.txt").read_text().splitlines()
        except FileNotFoundError as error:
            print("File missing:", error)
        return data

loader = FlipkartIssueDataLoader(DATA_DIR)
all_data = loader.load_all()

loader_summary = pd.DataFrame([
    {"dataset": name, "rows": len(df), "columns_or_text_lines": df.shape[1] if hasattr(df, "shape") else len(df)}
    for name, df in all_data.items()])
display(loader_summary)

log_fix("Section 5", "Wrong file names/formats, 3 files not loaded", "Correct reader for CSV, Excel, JSON, TXT", f"{len(all_data)} datasets loaded")

      dataset  rows  columns_or_text_lines
0      orders  5000                     14
1   customers  1200                      6
2     sellers  1000                      6
3     refunds  1300                      8
4  complaints  1500                      8
5     tickets  1500                      8
6       notes   100                    100

## Section 6: Data Validation and Relationship Checks

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`
- `customers.csv`
- `sellers.csv`
- `refunds.xlsx`
- `customer_complaints.json`
- `support_tickets.csv`

**How to approach:**
- Check required columns.
- Check duplicate order IDs.
- Check customer/seller/order relationships.
- Flag invalid dates and suspicious amounts.

**Expected output format:**
- Validation summary table with check_name, status, issue_count, notes.

**Hint:**
- Do not delete invalid records silently; flag them as review items.

In [8]:
# SECTION 6 — Data validation
# BROKEN: Uses incorrect assumptions and does not validate relationships.

o, c, s = all_data["orders"], all_data["customers"], all_data["sellers"]
r, cp, t = all_data["refunds"], all_data["complaints"], all_data["tickets"]

checks = []
def check(name, count, note=""):
    checks.append({"check_name": name, "status": "PASS" if count == 0 else "REVIEW", "issue_count": int(count), "notes": note})

required = ["order_id", "customer_id", "seller_id", "order_date", "promised_delivery_date",
            "actual_delivery_date", "order_amount", "order_status", "delivery_city"]
amount = pd.to_numeric(o["order_amount"], errors="coerce")

check("orders: missing required columns", len([col for col in required if col not in o.columns]))
check("orders: duplicate order_id", o["order_id"].duplicated().sum(), "flagged, not deleted")
check("orders: customer not in customers", (~o["customer_id"].isin(c["customer_id"])).sum())
check("orders: seller not in sellers", (~o["seller_id"].isin(s["seller_id"])).sum())
check("refunds: order not in orders", (~r["order_id"].isin(o["order_id"])).sum())
check("complaints: order not in orders", (~cp["order_id"].isin(o["order_id"])).sum())
check("tickets: order not in orders", (~t["order_id"].isin(o["order_id"])).sum())
for col in ["promised_delivery_date", "actual_delivery_date"]:
    parsed = pd.to_datetime(o[col], errors="coerce", format="%Y-%m-%d")
    check(f"orders: invalid {col}", (o[col].notna() & parsed.isna()).sum(), "e.g. not_available, 2026-31-05")
check("orders: amount missing/zero/negative", (amount.fillna(0) <= 0).sum())
check("refunds: refund_amount zero/negative", (r["refund_amount"] <= 0).sum())
check("tickets: resolution_time missing", t["resolution_time_hours"].isna().sum())

validation_summary = pd.DataFrame(checks)
display(validation_summary)

review_items_df = o[o["order_id"].duplicated(keep=False) | ~o["customer_id"].isin(c["customer_id"])
                    | ~o["seller_id"].isin(s["seller_id"]) | (amount.fillna(0) <= 0)]
print("Orders flagged for review (not deleted):", len(review_items_df))

log_fix("Section 6", "Wrong column names, no relationship/date/amount checks", "Added 12 checks + review table", validation_summary["status"].value_counts().to_dict())
# TODO:
# - validate order_id uniqueness
# - validate customer_id and seller_id relationship quality
# - validate refund/complaint/ticket order links
# - flag invalid dates and suspicious amounts

                                check_name  status  issue_count                           notes
0         orders: missing required columns    PASS            0
1               orders: duplicate order_id  REVIEW           16            flagged, not deleted
2        orders: customer not in customers  REVIEW           40
3            orders: seller not in sellers  REVIEW           30
4             refunds: order not in orders  REVIEW           23
5          complaints: order not in orders  REVIEW           36
6             tickets: order not in orders  REVIEW           25
7   orders: invalid promised_delivery_date  REVIEW           14  e.g. not_available, 2026-31-05
8     orders: invalid actual_delivery_date    PASS            0  e.g. not_available, 2026-31-05
9     orders: amount missing/zero/negative  REVIEW           25
10    refunds: refund_amount zero/negative  REVIEW           23
11        tickets: resolution_time missing  REVIEW          151

Orders flagged for review (not deleted): 124

## Section 7: Data Cleaning and Standardization

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `All loaded datasets`

**How to approach:**
- Standardize text statuses.
- Trim whitespace and normalize casing.
- Parse dates using safe coercion.
- Convert amount and time columns to numeric.

**Expected output format:**
- Cleaning summary table.
- Cleaned DataFrame preview.

**Hint:**
- Use helper functions so cleaning logic is not repeated across every dataset.

In [9]:
# SECTION 7 — Cleaning and standardization
# BROKEN: This code mutates only one column and ignores dates, amounts, and other files.

def clean_text(s):
    """Spaces/underscore hatao aur har label ki sabse common spelling use karo."""
    s = s.str.strip().str.replace("_", " ")
    best = s.groupby(s.str.lower()).agg(lambda x: x.value_counts().index[0])
    return s.str.lower().map(best)

def clean_date(s):
    d = pd.to_datetime(s, errors="coerce", format="%Y-%m-%d")
    swapped = pd.to_datetime(s, errors="coerce", format="%Y-%d-%m")
    return d.fillna(swapped)

orders_clean = all_data["orders"].copy()
for col in ["order_status", "payment_method", "delivery_city", "delay_reason", "seller_category"]:
    orders_clean[col] = clean_text(orders_clean[col])
for col in ["order_date", "promised_delivery_date", "actual_delivery_date"]:
    orders_clean[col] = clean_date(orders_clean[col])
orders_clean["order_amount"] = pd.to_numeric(orders_clean["order_amount"], errors="coerce")
orders_clean["order_amount_valid"] = orders_clean["order_amount"].where(orders_clean["order_amount"] > 0)

customers_clean = all_data["customers"].copy()
customers_clean["customer_segment"] = clean_text(customers_clean["customer_segment"])
sellers_clean = all_data["sellers"].copy()

refunds_clean = all_data["refunds"].copy()
for col in ["refund_status", "refund_reason"]:
    refunds_clean[col] = clean_text(refunds_clean[col])
for col in ["refund_initiated_date", "refund_completed_date"]:
    refunds_clean[col] = clean_date(refunds_clean[col])

complaints_clean = all_data["complaints"].copy()
for col in ["complaint_type", "complaint_status", "sentiment_tag"]:
    complaints_clean[col] = clean_text(complaints_clean[col])
complaints_clean["complaint_date"] = clean_date(complaints_clean["complaint_date"])

tickets_clean = all_data["tickets"].copy()
for col in ["ticket_status", "assigned_team", "escalation_flag"]:
    tickets_clean[col] = clean_text(tickets_clean[col])
tickets_clean["ticket_created_date"] = clean_date(tickets_clean["ticket_created_date"])
tickets_clean["resolution_time_hours"] = pd.to_numeric(tickets_clean["resolution_time_hours"], errors="coerce")


REFERENCE_DATE = max(orders_clean["actual_delivery_date"].max(), refunds_clean["refund_completed_date"].max(),
                     complaints_clean["complaint_date"].max(), tickets_clean["ticket_created_date"].max())
print("REFERENCE_DATE:", REFERENCE_DATE.date())

cols = ["order_status", "payment_method", "delivery_city"]
cleaning_summary = pd.DataFrame({"column": cols,
                                 "unique_before": [all_data["orders"][col].nunique() for col in cols],
                                 "unique_after": [orders_clean[col].nunique() for col in cols]})
display(cleaning_summary)
display(orders_clean.head())

log_fix("Section 7", "Only order_status lowercased; dates, amounts, other files ignored", "clean_text + clean_date for all datasets", cleaning_summary.to_dict("records"))

# TODO:
# - trim whitespace
# - standardize casing and underscores
# - parse date columns safely
# - clean amount fields
# - standardize refund/complaint/ticket status fields
display(orders_clean.head())

REFERENCE_DATE: 2026-06-29

           column  unique_before  unique_after
0    order_status             28             7
1  payment_method             19             5
2   delivery_city             32            16

,order_id,customer_id,seller_id,order_date,order_time,promised_delivery_date,actual_delivery_date,order_amount,payment_method,order_status,delay_reason,delivery_city,device_type,seller_category,order_amount_valid
0,ORD0000001,CUST000771,SELL0475,2026-05-30,10:51:46,2026-06-03,2026-06-03,57056.16,Cash on Delivery,Delivered,NaN,Delhi,iOS,Electronics,57056.16
1,ORD0000002,CUST000122,SELL0035,2026-05-05,15:59:45,2026-05-08,2026-05-07,25038.34,UPI,Delivered,NaN,Gurugram,iOS,Grocery,25038.34
2,ORD0000003,CUST000784,SELL0785,2026-05-11,11:48:01,2026-05-15,NaT,29439.12,UPI,Processing,Warehouse Delay,Lucknow,Android,Grocery,29439.12
3,ORD0000004,CUST000288,SELL0211,2026-05-23,03:12:27,2026-05-27,2026-05-25,60697.51,Card,Delivered,NaN,Indore,Android,Beauty,60697.51
4,ORD0000005,CUST001168,SELL0981,2026-06-14,00:30:13,2026-06-19,NaT,56251.50,UPI,Cancelled,Payment Failed,Nagpur,Mobile Web,Beauty,56251.50

,order_id,customer_id,seller_id,order_date,order_time,promised_delivery_date,actual_delivery_date,order_amount,payment_method,order_status,delay_reason,delivery_city,device_type,seller_category,order_amount_valid
0,ORD0000001,CUST000771,SELL0475,2026-05-30,10:51:46,2026-06-03,2026-06-03,57056.16,Cash on Delivery,Delivered,NaN,Delhi,iOS,Electronics,57056.16
1,ORD0000002,CUST000122,SELL0035,2026-05-05,15:59:45,2026-05-08,2026-05-07,25038.34,UPI,Delivered,NaN,Gurugram,iOS,Grocery,25038.34
2,ORD0000003,CUST000784,SELL0785,2026-05-11,11:48:01,2026-05-15,NaT,29439.12,UPI,Processing,Warehouse Delay,Lucknow,Android,Grocery,29439.12
3,ORD0000004,CUST000288,SELL0211,2026-05-23,03:12:27,2026-05-27,2026-05-25,60697.51,Card,Delivered,NaN,Indore,Android,Beauty,60697.51
4,ORD0000005,CUST001168,SELL0981,2026-06-14,00:30:13,2026-06-19,NaT,56251.50,UPI,Cancelled,Payment Failed,Nagpur,Mobile Web,Beauty,56251.50

## Section 8: Order Delay Detection

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`

**How to approach:**
- Compare promised and actual delivery dates.
- Handle pending orders that breached promise date.
- Classify delay buckets.
- Summarize delays by bucket and city.

**Expected output format:**
- delay_summary DataFrame.
- city_delay_summary DataFrame.
- orders table with delivery_delay_days and delay_bucket.

**Hint:**
- Use `actual_delivery_date`, not `delivered_date`.

In [10]:
# SECTION 8 — Order delay detection
# BROKEN: The formula uses a non-existent column and misses pending promised-date breaches.

promised = orders_clean["promised_delivery_date"]
actual = orders_clean["actual_delivery_date"]
status = orders_clean["order_status"]
pending = status.eq("Processing")


orders_clean["delivery_delay_days"] = (actual - promised).dt.days
orders_clean.loc[pending, "delivery_delay_days"] = (REFERENCE_DATE - promised[pending]).dt.days
d = orders_clean["delivery_delay_days"]

orders_clean["delay_bucket"] = np.select(
    [status.eq("Cancelled"), status.eq("Lost"), promised.isna(), pending & (d > 0), d <= 0, d <= 2, d <= 5],
    ["Cancelled", "Lost", "Unknown", "Pending - Breached", "On Time", "Minor", "Moderate"],
    default="Severe")

delay_summary = orders_clean["delay_bucket"].value_counts().reset_index()
delay_summary.columns = ["delay_bucket", "orders"]
display(delay_summary)

city_delay_summary = (orders_clean[d.notna()].assign(delayed=lambda x: x["delivery_delay_days"] > 0)
    .groupby("delivery_city")
    .agg(orders=("order_id", "size"), delayed=("delayed", "sum"), avg_delay_days=("delivery_delay_days", "mean"))
    .assign(delay_rate_pct=lambda x: (x["delayed"] / x["orders"] * 100).round(1))
    .round(1).sort_values("delay_rate_pct", ascending=False))
display(city_delay_summary)
display(orders_clean[["order_id", "order_status", "delivery_city", "delivery_delay_days", "delay_bucket"]].head())

log_fix("Section 8", "Non-existent delivered_date column; pending orders ignored", "Used actual_delivery_date + pending vs REFERENCE_DATE + buckets", delay_summary.set_index("delay_bucket")["orders"].to_dict())
# TODO:
# - use actual_delivery_date
# - handle invalid dates
# - handle missing actual delivery for pending orders
# - create delay buckets

         delay_bucket  orders
0             On Time    2232
1               Minor     765
2              Severe     583
3           Cancelled     488
4  Pending - Breached     437
5            Moderate     401
6                Lost      86
7             Unknown       8

               orders  delayed  avg_delay_days  delay_rate_pct
delivery_city
Indore            276      150             4.8            54.3
Hyderabad         254      137             5.2            53.9
Lucknow           273      141             5.2            51.6
Pune              280      143             5.1            51.1
Coimbatore        271      138             4.7            50.9
Nagpur            275      139             4.5            50.5
Noida             286      143             4.3            50.0
Chennai           301      150             5.3            49.8
Kochi             267      133             5.8            49.8
Mumbai            278      138             4.2            49.6
Ahmedabad         275      133             4.2            48.4
Bengaluru         253      121             4.1            47.8
Gurugram          282      132             4.0            46.8
Kolkata           271      126             3.3            46.5
Delhi             285      130             4.4            45.6
Jaipur            291      132             3.7            45.4

     order_id order_status delivery_city  delivery_delay_days        delay_bucket
0  ORD0000001    Delivered         Delhi                  0.0             On Time
1  ORD0000002    Delivered      Gurugram                 -1.0             On Time
2  ORD0000003   Processing       Lucknow                 45.0  Pending - Breached
3  ORD0000004    Delivered        Indore                 -2.0             On Time
4  ORD0000005    Cancelled        Nagpur                  NaN           Cancelled

## Section 9: Refund Delay and Refund-Priority Analysis

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `refunds.xlsx`
- `orders.csv`

**How to approach:**
- Parse refund dates.
- Calculate refund age.
- Detect pending/failed refunds.
- Detect refund SLA breaches and amount mismatches.

**Expected output format:**
- refund_summary table.
- refunds table with refund_priority_candidate and flags.

**Hint:**
- A pending refund needs age calculated against a reference date.

In [11]:
# SECTION 9 — Refund delay and refund-priority analysis
# BROKEN: refunds dataframe is not loaded correctly and business rules are missing.

refunds_df = refunds_clean.copy()
order_amount = orders_clean.drop_duplicates("order_id").set_index("order_id")["order_amount_valid"]
refunds_df["order_amount"] = refunds_df["order_id"].map(order_amount)


end_date = refunds_df["refund_completed_date"].fillna(REFERENCE_DATE)
refunds_df["refund_age_days"] = (end_date - refunds_df["refund_initiated_date"]).dt.days

s = refunds_df["refund_status"]
refunds_df["is_open"] = s.isin(["Pending", "Initiated"])
refunds_df["is_failed"] = s.eq("Failed")
refunds_df["sla_breach"] = (refunds_df["refund_age_days"] > REFUND_SLA_DAYS) & s.ne("Not Applicable")
refunds_df["open_breach"] = refunds_df["is_open"] & refunds_df["sla_breach"]
refunds_df["amount_mismatch"] = (refunds_df["refund_amount"] - refunds_df["order_amount"]).abs() > 1
refunds_df["refund_exceeds_order"] = refunds_df["refund_amount"] > refunds_df["order_amount"] + 1
refunds_df["refund_priority_candidate"] = refunds_df["is_failed"] | refunds_df["open_breach"] | refunds_df["refund_exceeds_order"]

refund_summary = (refunds_df.groupby("refund_status")
    .agg(refunds=("refund_id", "size"), avg_age_days=("refund_age_days", "mean"), sla_breaches=("sla_breach", "sum"),
         amount_mismatches=("amount_mismatch", "sum"), priority_candidates=("refund_priority_candidate", "sum"))
    .round(1))
display(refund_summary)
display(refunds_df[refunds_df["refund_priority_candidate"]].head(5)[["refund_id", "order_id", "refund_status", "refund_age_days", "refund_priority_candidate"]])

log_fix("Section 9", "Refunds not loaded correctly, no business rules", "Added age, SLA, failed, amount mismatch, priority flag", int(refunds_df["refund_priority_candidate"].sum()))
# TODO:
# - parse refund dates
# - standardize refund status
# - detect pending and failed refunds
# - detect refund SLA breaches
# - detect amount mismatch against order amount
display(refunds_df.head())

                refunds  avg_age_days  sla_breaches  amount_mismatches  priority_candidates
refund_status
Failed              136          15.6            71                 59                  136
Initiated           135          33.0           133                 68                  133
Not Applicable       74          32.4             0                 35                   15
Pending             299          34.0           295                141                  297
Processed           571           3.9             0                292                  116
Rejected             85          15.5            43                 43                   15

   refund_id    order_id refund_status  refund_age_days  refund_priority_candidate
1  REF000002  ORD0001547     Initiated             18.0                       True
3  REF000004  ORD0000632       Pending             14.0                       True
5  REF000006  ORD0000941     Processed              1.0                       True
6  REF000007  ORD0003554        Failed              5.0                       True
7  REF000008  ORD0000024       Pending             40.0                       True

,refund_id,order_id,refund_status,refund_amount,refund_initiated_date,refund_completed_date,refund_reason,refund_channel,order_amount,refund_age_days,is_open,is_failed,sla_breach,open_breach,amount_mismatch,refund_exceeds_order,refund_priority_candidate
0,REF000001,ORD0000498,Rejected,44569.30,2026-05-08,2026-05-16,Damaged Product,Card,44569.30,8.0,False,False,True,False,False,False,False
1,REF000002,ORD0001547,Initiated,40965.07,2026-06-11,NaT,Damaged Product,UPI,37240.97,18.0,True,False,True,True,True,True,True
2,REF000003,ORD0003579,Processed,14072.25,2026-05-11,2026-05-18,Payment Issue,Card,28144.51,7.0,False,False,False,False,True,False,False
3,REF000004,ORD0000632,Pending,45492.77,2026-06-15,NaT,Returned Item,UPI,45492.77,14.0,True,False,True,True,False,False,True
4,REF000005,ORD0000671,Processed,42444.88,2026-05-26,2026-05-29,Wrong Item,Wallet,42444.88,3.0,False,False,False,False,False,False,False

## Section 10: Customer Complaint Linking

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `customer_complaints.json`
- `orders.csv`
- `customers.csv`

**How to approach:**
- Aggregate complaints by order_id.
- Count negative or angry complaints.
- Detect repeated complaints.
- Create complaint type summary.

**Expected output format:**
- complaints_order table.
- complaint_type_summary table.

**Hint:**
- Aggregate before merging into the order-level feature table.

In [12]:
# SECTION 10 — Customer complaint linking
# BROKEN: Complaint data has not been loaded and aggregation is missing.

complaints_df = complaints_clean.copy()
complaints_df["is_negative"] = complaints_df["sentiment_tag"].isin(["Negative", "Angry"])
complaints_df["is_angry"] = complaints_df["sentiment_tag"].eq("Angry")
complaints_df["is_open"] = complaints_df["complaint_status"].isin(["Open", "Escalated", "Reopened"])


complaints_order = (complaints_df.groupby("order_id")
    .agg(complaint_count=("complaint_id", "count"), negative_complaints=("is_negative", "sum"),
         angry_complaints=("is_angry", "sum"), open_complaints=("is_open", "sum"))
    .reset_index())
print("Orders with repeated complaints:", (complaints_order["complaint_count"] > 1).sum())


complaints_view = (complaints_order
    .merge(orders_clean.drop_duplicates("order_id")[["order_id", "customer_id", "delivery_city"]], on="order_id", how="left")
    .merge(customers_clean[["customer_id", "customer_segment"]], on="customer_id", how="left"))
display(complaints_view.sort_values("complaint_count", ascending=False).head())

complaint_type_summary = (complaints_df.groupby("complaint_type")
    .agg(complaints=("complaint_id", "count"), negative=("is_negative", "sum"), open=("is_open", "sum"))
    .sort_values("complaints", ascending=False))
display(complaint_type_summary)

log_fix("Section 10", "Complaints not loaded; wrong column 'order'", "Grouped by order_id with negative/angry/open counts", f"{len(complaints_order)} orders with complaints")
# TODO:
# - use order_id
# - aggregate complaint count by order
# - detect repeated complaints
# - summarize sentiment
# - flag angry or negative complaint signals

Orders with repeated complaints: 183

       order_id  complaint_count  negative_complaints  angry_complaints  open_complaints customer_id delivery_city customer_segment
268  ORD0001028                4                    3                 2                4  CUST001018         Noida          Regular
567  ORD0002260                4                    0                 0                2  CUST000286     Hyderabad          Regular
54   ORD0000207                3                    1                 0                1  CUST001095        Jaipur             Plus
143  ORD0000544                3                    3                 0                1  CUST000815       Lucknow          Regular
57   ORD0000213                3                    1                 0                1  CUST001191     Bengaluru          Regular

                        complaints  negative  open
complaint_type
Refund Delay                   196       143    93
Cancellation Issue             194       128    89
Damaged Product                194       114    90
Wrong Item                     193       118    96
Late Delivery                  187       123    88
Payment Deducted Twice         183       112    83
Seller Issue                   177       107    88
Missing Item                   176       114    86

## Section 11: Support Ticket Mapping

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `support_tickets.csv`
- `orders.csv`

**How to approach:**
- Standardize ticket status.
- Flag escalations.
- Create SLA breach logic.
- Aggregate ticket signals by order_id.

**Expected output format:**
- tickets_order table.
- ticket_team_summary table.

**Hint:**
- Use `resolution_time_hours`, not `resolution_hours`.

In [14]:
# SECTION 11 — Support ticket mapping
# BROKEN: The code uses wrong column names and has no SLA logic.

tickets_df = tickets_clean.copy()
tickets_df["is_escalated"] = tickets_df["escalation_flag"].eq("Yes") | tickets_df["ticket_status"].eq("Escalated")
tickets_df["is_unresolved"] = ~tickets_df["ticket_status"].isin(["Resolved", "Closed"])
tickets_df["ticket_sla_breach"] = tickets_df["resolution_time_hours"] > TICKET_SLA_HOURS

tickets_order = (tickets_df.groupby("order_id")
    .agg(ticket_count=("ticket_id", "count"), escalated_tickets=("is_escalated", "sum"),
         ticket_sla_breaches=("ticket_sla_breach", "sum"), unresolved_tickets=("is_unresolved", "sum"))
    .reset_index())
display(tickets_order.sort_values("ticket_count", ascending=False).head())

ticket_team_summary = (tickets_df.groupby("assigned_team")
    .agg(tickets=("ticket_id", "count"), escalated=("is_escalated", "sum"), sla_breaches=("ticket_sla_breach", "sum"),
         avg_resolution_hours=("resolution_time_hours", "mean"))
    .round(1))
display(ticket_team_summary)

log_fix("Section 11", "Wrong column resolution_hours, no SLA/escalation logic", f"SLA = {TICKET_SLA_HOURS}h, escalation flag, order-level aggregate", f"{len(tickets_order)} orders with tickets")

# TODO:
# - use resolution_time_hours
# - standardize ticket status
# - detect escalated tickets
# - aggregate ticket count and SLA breach by order

       order_id  ticket_count  escalated_tickets  ticket_sla_breaches  unresolved_tickets
856  ORD0003389             4                  2                    2                   1
911  ORD0003605             3                  0                    2                   2
143  ORD0000558             3                  2                    1                   2
542  ORD0002108             3                  0                    3                   1
15   ORD0000054             3                  1                    1                   2

                 tickets  escalated  sla_breaches  avg_resolution_hours
assigned_team
City Ops             260         81           175                  90.7
Escalation Desk      222         73           143                  87.4
Logistics Ops        253         84           170                  94.4
Refund Ops           264         85           184                  95.9
Seller Ops           267         77           178                  92.6
Support Ops          234         79           160                  89.8

## Section 12: Duplicate and Repeat Issue Detection

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`
- `customer_complaints.json`
- `support_tickets.csv`

**How to approach:**
- Find duplicate order IDs.
- Find duplicate-looking order patterns.
- Find customers with repeated complaints.
- Summarize issue counts.

**Expected output format:**
- duplicate_summary table.
- Optional preview of repeated complaint customers.

**Hint:**
- Duplicate-looking records may share customer, seller, date, and amount even if row IDs differ.

In [15]:
# SECTION 12 — Duplicate and repeat issue detection
# BROKEN: This only checks raw duplicated rows and misses duplicate-looking orders.

duplicate_summary = pd.DataFrame({
    "check": ["Duplicate order IDs",
              "Duplicate-looking orders (same customer + seller + date + amount)",
              "Customers with repeated complaints",
              "Orders with repeated tickets"],
    "count": [orders_clean["order_id"].duplicated().sum(),
              orders_clean.duplicated(["customer_id", "seller_id", "order_date", "order_amount"]).sum(),
              (complaints_df.groupby("customer_id").size() > 1).sum(),
              (tickets_order["ticket_count"] > 1).sum()]})
display(duplicate_summary)

print("Customers with most complaints:")
display(complaints_df.groupby("customer_id").size().sort_values(ascending=False).head(5).rename("complaints"))

log_fix("Section 12", "Only exact duplicate rows were checked", "Checked duplicate IDs, duplicate-looking orders, repeat complaints/tickets", duplicate_summary["count"].tolist())

# TODO:
# - duplicate order IDs
# - duplicate-looking customer/seller/date/amount patterns
# - repeated complaints for same customer
# - repeated support issues for same order

                                                               check  count
0                                                Duplicate order IDs     16
1  Duplicate-looking orders (same customer + seller + date + amount)      0
2                                 Customers with repeated complaints    412
3                                       Orders with repeated tickets    197

Customers with most complaints:

customer_id
CUST000364    7
CUST000664    6
CUST000829    6
CUST000973    6
CUST001098    5
Name: complaints, dtype: int64

## Section 13: Final Feature Table / Master Merge

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `orders.csv`
- `customers.csv`
- `sellers.csv`
- `refunds.xlsx`
- `customer_complaints.json`
- `support_tickets.csv`

**How to approach:**
- Aggregate many-to-one tables first.
- Merge customer and seller master data.
- Merge aggregated refund/complaint/ticket features.
- Validate row count before and after merge.

**Expected output format:**
- final_feature_table DataFrame.
- merge_validation table.

**Hint:**
- Raw refund, complaint, and ticket merges can multiply rows if not aggregated first.

In [17]:
# SECTION 13 — Final feature table
# BROKEN: Raw merges can accidentally multiply rows.


refund_by_order = (refunds_df.groupby("order_id")
    .agg(refund_count=("refund_id", "count"), refund_failed=("is_failed", "sum"), refund_open_breach=("open_breach", "sum"),
         refund_exceeds=("refund_exceeds_order", "sum"), refund_max_age_days=("refund_age_days", "max"),
         refund_total=("refund_amount", "sum"), refund_priority_count=("refund_priority_candidate", "sum"))
    .reset_index())

final_feature_table = (orders_clean
    .merge(customers_clean[["customer_id", "customer_name", "customer_segment"]], on="customer_id", how="left")
    .merge(sellers_clean[["seller_id", "seller_name", "seller_rating"]], on="seller_id", how="left")
    .merge(refund_by_order, on="order_id", how="left")
    .merge(complaints_order, on="order_id", how="left")
    .merge(tickets_order, on="order_id", how="left"))


agg_cols = [col for table in (refund_by_order, complaints_order, tickets_order) for col in table.columns if col != "order_id"]
final_feature_table[agg_cols] = final_feature_table[agg_cols].fillna(0)
final_feature_table["customer_segment"] = final_feature_table["customer_segment"].fillna("Unknown")
final_feature_table["customer_name"] = final_feature_table["customer_name"].fillna("Customer")

merge_validation = pd.DataFrame([{"orders_rows": len(orders_clean), "final_rows": len(final_feature_table),
                                  "row_count_ok": len(orders_clean) == len(final_feature_table)}])
display(merge_validation)
display(final_feature_table[["order_id", "customer_segment", "delay_bucket", "refund_count", "complaint_count", "ticket_count"]].head())

log_fix("Section 13", "Raw merges multiply rows", "Aggregated refunds/complaints/tickets first, then merged", merge_validation.to_dict("records"))

# TODO:
# - aggregate refunds, complaints, and tickets before merging
# - merge customer and seller master data
# - prevent accidental row explosion

   orders_rows  final_rows  row_count_ok
0         5000        5000          True

     order_id customer_segment        delay_bucket  refund_count  complaint_count  ticket_count
0  ORD0000001          Regular             On Time           0.0              2.0           0.0
1  ORD0000002          Regular             On Time           1.0              0.0           0.0
2  ORD0000003          Regular  Pending - Breached           0.0              0.0           0.0
3  ORD0000004          Regular             On Time           0.0              0.0           0.0
4  ORD0000005          Regular           Cancelled           1.0              0.0           3.0

## Section 14: Priority Classification

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `final_feature_table`

**How to approach:**
- Create a scoring function.
- Combine delay, refund, complaint, ticket, and customer segment signals.
- Return priority level and reasons.

**Expected output format:**
- priority_summary table.
- final_feature_table with issue_score, issue_priority, priority_reasons.

**Hint:**
- Priority should not be based on delay alone.

In [18]:
# SECTION 14 — Priority classification
# BROKEN: Priority logic is too shallow and ignores PRD rules.

def score_case(row):

    rules = [
        (3, row["delay_bucket"] == "Lost", "Shipment lost"),
        (3, row["delay_bucket"] == "Pending - Breached", "Order stuck past promised date"),
        (2, row["delay_bucket"] == "Severe", "Severe delivery delay"),
        (1, row["delay_bucket"] == "Moderate", "Moderate delivery delay"),
        (3, row["refund_failed"] > 0, "Refund failed"),
        (3, row["refund_open_breach"] > 0, "Open refund past SLA"),
        (2, row["refund_exceeds"] > 0, "Refund exceeds order amount"),
        (2, row["angry_complaints"] > 0, "Angry customer"),
        (1, row["angry_complaints"] == 0 and row["negative_complaints"] > 0, "Negative complaint"),
        (2, row["complaint_count"] > 1, "Repeated complaints"),
        (1, row["open_complaints"] > 0, "Complaint still open"),
        (2, row["escalated_tickets"] > 0, "Escalated ticket"),
        (1, row["ticket_sla_breaches"] > 0, "Ticket SLA breached"),
        (1, row["customer_segment"] in ("Premium", "Plus", "Business"), "Priority customer segment"),
    ]
    score = sum(points for points, cond, _ in rules if cond)
    reasons = "; ".join(reason for _, cond, reason in rules if cond) or "No active issue"
    priority = "High" if score >= 8 else "Medium" if score >= 4 else "Low"
    return pd.Series([score, priority, reasons], index=["issue_score", "issue_priority", "priority_reasons"])

final_feature_table[["issue_score", "issue_priority", "priority_reasons"]] = final_feature_table.apply(score_case, axis=1)

priority_summary = (final_feature_table.groupby("issue_priority")
    .agg(cases=("order_id", "size"), avg_score=("issue_score", "mean")).round(1)
    .reindex(["High", "Medium", "Low"]))
display(priority_summary)
display(final_feature_table.sort_values("issue_score", ascending=False)[["order_id", "issue_score", "issue_priority", "priority_reasons"]].head())

log_fix("Section 14", "Priority used delay only", "Score from delay, refund, complaint, ticket, customer segment + reasons", priority_summary["cases"].to_dict())

# TODO:
# - use delay severity
# - refund status and refund age
# - complaints and sentiment
# - ticket escalation and SLA
# - customer impact
display(final_feature_table[["order_id", "issue_priority"]].head())

                cases  avg_score
issue_priority
High              122        8.8
Medium           1180        4.9
Low              3698        1.3

        order_id  issue_score issue_priority                                                                           priority_reasons
4300  ORD0004301           13           High  Refund failed; Open refund past SLA; Refund exceeds order amount; Negative complaint; ...
2686  ORD0002687           13           High  Order stuck past promised date; Open refund past SLA; Angry customer; Repeated complai...
3695  ORD0003696           13           High  Order stuck past promised date; Refund failed; Open refund past SLA; Refund exceeds or...
749   ORD0000750           12           High  Severe delivery delay; Refund failed; Open refund past SLA; Negative complaint; Repeat...
421   ORD0000422           12           High  Order stuck past promised date; Open refund past SLA; Refund exceeds order amount; Esc...

     order_id issue_priority
0  ORD0000001         Medium
1  ORD0000002            Low
2  ORD0000003            Low
3  ORD0000004            Low
4  ORD0000005         Medium

## Section 15: Recommended Action Generator

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `final_feature_table`

**How to approach:**
- Create a function that reads priority and reasons.
- Return specific support/refund/seller/city actions.
- Add recommended_action to final table.

**Expected output format:**
- Action summary table.
- Preview with order_id, priority, action.

**Hint:**
- Recommendations should help a support lead decide what to do next.

In [19]:
# SECTION 15 — Recommended action generator
# BROKEN: Recommendations are generic and not tied to business signals.

def recommend_action(row):
    if row["escalated_tickets"] > 0: return "Escalation Desk: call customer back using merged complaint + ticket view"
    if row["refund_failed"] > 0: return "Refund Ops: re-initiate failed refund and confirm with customer"
    if row["refund_open_breach"] > 0: return "Refund Ops: release pending refund (SLA breached)"
    if row["refund_exceeds"] > 0: return "Refund Ops: reconcile refund amount with order amount"
    if row["angry_complaints"] > 0 or row["complaint_count"] > 1: return "Support Ops: senior agent callback and resolution timeline"
    if row["delay_bucket"] == "Lost": return "Logistics Ops: raise lost-shipment claim, offer reship or refund"
    if row["delay_bucket"] == "Pending - Breached":
        team = "Seller Ops" if "Seller" in str(row["delay_reason"]) else "City Ops"
        return f"{team}: dispatch or cancel the stuck order ({row['delay_reason']})"
    if row["delay_bucket"] in ("Severe", "Moderate"): return f"City Ops: review courier delays in {row['delivery_city']}"
    return "None: no action needed, monitor"

final_feature_table["recommended_action"] = final_feature_table.apply(recommend_action, axis=1)
final_feature_table["action_owner"] = final_feature_table["recommended_action"].str.split(":").str[0]

action_summary = pd.crosstab(final_feature_table["action_owner"], final_feature_table["issue_priority"])
display(action_summary)
display(final_feature_table.sort_values("issue_score", ascending=False)[["order_id", "issue_priority", "recommended_action"]].head())

log_fix("Section 15", "Generic 'Review order' action", "Team-specific actions from business signals", final_feature_table["action_owner"].value_counts().to_dict())

# TODO:
# - create specific actions for refund operations, support, seller ops, and city ops
display(final_feature_table[["order_id", "issue_priority", "recommended_action"]].head())

issue_priority   High   Low  Medium
action_owner
City Ops            0   715     211
Escalation Desk    48   138     269
Logistics Ops       0    22      42
None                0  2517       7
Refund Ops         58   160     371
Seller Ops          0    35      60
Support Ops        16   111     220

        order_id issue_priority                                                        recommended_action
4300  ORD0004301           High           Refund Ops: re-initiate failed refund and confirm with customer
2686  ORD0002687           High  Escalation Desk: call customer back using merged complaint + ticket view
3695  ORD0003696           High  Escalation Desk: call customer back using merged complaint + ticket view
749   ORD0000750           High           Refund Ops: re-initiate failed refund and confirm with customer
421   ORD0000422           High  Escalation Desk: call customer back using merged complaint + ticket view

     order_id issue_priority                                                        recommended_action
0  ORD0000001         Medium                Support Ops: senior agent callback and resolution timeline
1  ORD0000002            Low                         Refund Ops: release pending refund (SLA breached)
2  ORD0000003            Low            City Ops: dispatch or cancel the stuck order (Warehouse Delay)
3  ORD0000004            Low                                           None: no action needed, monitor
4  ORD0000005         Medium  Escalation Desk: call customer back using merged complaint + ticket view

## Section 16: AI-Ready Prompt Generator

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `final_feature_table`

**How to approach:**
- Create structured prompts from case data.
- Include only available facts.
- Do not call external APIs.
- Add prompt preview column.

**Expected output format:**
- Preview table with order_id and ai_prompt_preview.

**Hint:**
- This is prompt generation only, not AI integration.

In [20]:
# SECTION 16 — AI-ready prompt generator
# BROKEN: This should create a useful prompt, not call an external API.

def create_ai_prompt(row):
    amount = f"INR {row['order_amount_valid']:,.0f}" if pd.notna(row["order_amount_valid"]) else "not available"
    return (f"You are a Flipkart support agent. Write a short, polite message (max 100 words) to {row['customer_name']}.\n"
            f"Order {row['order_id']} | status: {row['order_status']} | city: {row['delivery_city']} | amount: {amount}\n"
            f"Delivery: {row['delay_bucket']} | refunds: {int(row['refund_count'])} (failed: {int(row['refund_failed'])}) | "
            f"complaints: {int(row['complaint_count'])} | tickets: {int(row['ticket_count'])}\n"
            f"Issues: {row['priority_reasons']}\n"
            f"Action to communicate: {row['recommended_action']}\n"
            "Do not promise anything beyond this action.")

final_feature_table["ai_prompt"] = final_feature_table.apply(create_ai_prompt, axis=1)
final_feature_table["ai_prompt_preview"] = final_feature_table["ai_prompt"].str[:150] + "..."
display(final_feature_table.sort_values("issue_score", ascending=False)[["order_id", "ai_prompt_preview"]].head())

log_fix("Section 16", "Placeholder prompt", "Structured prompt from case facts (no API call)", f"{len(final_feature_table)} prompts")
# TODO:
# - include order context
# - include delay/refund/complaint/ticket signals
# - include requested support action
# - do not call any AI API
display(final_feature_table[["order_id", "ai_prompt_preview"]].head())

        order_id                                                                          ai_prompt_preview
4300  ORD0004301  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Ani...
2686  ORD0002687  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Diy...
3695  ORD0003696  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Ana...
749   ORD0000750  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Sai...
421   ORD0000422  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Viv...

     order_id                                                                          ai_prompt_preview
0  ORD0000001  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Ish...
1  ORD0000002  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Adi...
2  ORD0000003  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Viv...
3  ORD0000004  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Aar...
4  ORD0000005  You are a Flipkart support agent. Write a short, polite message (max 100 words) to Ish...

## Section 17: Colab GUI/Search/Filter Experience

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `final_feature_table`

**How to approach:**
- Use ipywidgets or equivalent.
- Allow filtering by priority, city, and ID search.
- Display a compact case table.

**Expected output format:**
- Interactive widget or fallback output.
- Filtered case preview.

**Hint:**
- The GUI should make the notebook feel like an internal tool.

In [21]:
# SECTION 17 — Colab GUI/search/filter experience
# BROKEN: Incomplete widgets and no connected output.

import ipywidgets as widgets
from IPython.display import display

show_cols = ["order_id", "delivery_city", "order_status", "issue_priority", "issue_score", "recommended_action"]
priority_dropdown = widgets.Dropdown(options=["All", "High", "Medium", "Low"], description="Priority")
city_dropdown = widgets.Dropdown(options=["All"] + sorted(final_feature_table["delivery_city"].unique()), description="City")
search_box = widgets.Text(description="Order ID")
output = widgets.Output()

def show_cases(change=None):
    df = final_feature_table
    if priority_dropdown.value != "All": df = df[df["issue_priority"] == priority_dropdown.value]
    if city_dropdown.value != "All": df = df[df["delivery_city"] == city_dropdown.value]
    if search_box.value: df = df[df["order_id"].str.contains(search_box.value.strip().upper())]
    with output:
        output.clear_output()
        print(len(df), "cases found")
        display(df.sort_values("issue_score", ascending=False)[show_cols].head(15))

for widget in (priority_dropdown, city_dropdown, search_box):
    widget.observe(show_cases, names="value")

display(priority_dropdown, city_dropdown, search_box, output)
show_cases()

log_fix("Section 17", "Widgets not connected to data", "Dropdown + search box filter final_feature_table", "priority, city, order ID filters")
# TODO:
# - connect filters to final_feature_table
# - display matching rows
# - support city or priority filters
display(priority_dropdown, search_box)

Dropdown(description='Priority', options=('All', 'High', 'Medium', 'Low'), value='All')

Dropdown(description='City', options=('All', 'Ahmedabad', 'Bengaluru', 'Chennai', 'Coimbatore', 'Delhi', 'Guru…

Text(value='', description='Order ID')

Output()

Dropdown(description='Priority', options=('All', 'High', 'Medium', 'Low'), value='All')

Text(value='', description='Order ID')

## Section 18: Final Report Export and Preview

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `final_feature_table`

**How to approach:**
- Select required report schema columns.
- Add generated timestamp.
- Export final CSV.
- Preview top priority cases.

**Expected output format:**
- final_issue_resolution_report.csv.
- Priority summary table.
- Final report preview.

**Hint:**
- The final report should include business signals, not just IDs.

In [22]:
# SECTION 18 — Final report export and preview
# BROKEN: Required report columns are missing and file export is incomplete.

REPORT_FILE = "final_issue_resolution_report.csv"
report_columns = ["order_id", "customer_id", "customer_name", "customer_segment", "seller_id", "delivery_city", "order_status",
                  "order_amount", "delay_bucket", "delivery_delay_days", "refund_count", "refund_failed", "complaint_count",
                  "ticket_count", "issue_score", "issue_priority", "priority_reasons", "recommended_action", "action_owner"]

final_report = final_feature_table[report_columns].sort_values("issue_score", ascending=False).copy()
final_report["report_generated_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
final_report.to_csv(REPORT_FILE, index=False)

print("Saved:", REPORT_FILE, "| shape:", final_report.shape)
display(priority_summary)
display(final_report.head(10))

log_fix("Section 18", "Report had only 2 columns, no export", "Full schema + timestamp, saved CSV", final_report.shape)

# TODO:
# - include all required final report schema columns
# - add generated timestamp
# - export final_issue_resolution_report.csv
# - preview top priority cases
display(final_report.head())

Saved: final_issue_resolution_report.csv | shape: (5000, 20)

                cases  avg_score
issue_priority
High              122        8.8
Medium           1180        4.9
Low              3698        1.3

,order_id,customer_id,customer_name,customer_segment,seller_id,delivery_city,order_status,order_amount,delay_bucket,delivery_delay_days,refund_count,refund_failed,complaint_count,ticket_count,issue_score,issue_priority,priority_reasons,recommended_action,action_owner,report_generated_at
4300,ORD0004301,CUST000490,Anika Chopra,Premium,SELL0189,Bengaluru,Delivered,62080.09,On Time,-1.0,4.0,1.0,2.0,0.0,13,High,Refund failed; Open refund past SLA; Refund exceeds order amount; Negative complaint; ...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
2686,ORD0002687,CUST000018,Diya Singh,Regular,SELL0553,Kochi,Processing,23047.07,Pending - Breached,51.0,2.0,0.0,2.0,1.0,13,High,Order stuck past promised date; Open refund past SLA; Angry customer; Repeated complai...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
3695,ORD0003696,CUST000395,Ananya Verma,Regular,SELL0307,Chennai,Processing,59530.80,Pending - Breached,12.0,3.0,1.0,0.0,1.0,13,High,Order stuck past promised date; Refund failed; Open refund past SLA; Refund exceeds or...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
749,ORD0000750,CUST000431,Sai Khan,Regular,SELL0567,Mumbai,Delayed,40173.12,Severe,9.0,2.0,1.0,2.0,1.0,12,High,Severe delivery delay; Refund failed; Open refund past SLA; Negative complaint; Repeat...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
421,ORD0000422,CUST000756,Vivaan Ghosh,Business,SELL0957,Mumbai,Processing,46937.94,Pending - Breached,15.0,2.0,0.0,0.0,1.0,12,High,Order stuck past promised date; Open refund past SLA; Refund exceeds order amount; Esc...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
44,ORD0000045,CUST000413,Rohan Agarwal,Premium,SELL0358,Hyderabad,Returned,28967.17,Severe,8.0,2.0,1.0,0.0,0.0,11,High,Severe delivery delay; Refund failed; Open refund past SLA; Refund exceeds order amoun...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
1081,ORD0001082,CUST000396,Neha Verma,Regular,SELL0114,Gurugram,Refund Pending,37625.43,Severe,7.0,2.0,0.0,1.0,1.0,11,High,Severe delivery delay; Open refund past SLA; Refund exceeds order amount; Negative com...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
3922,ORD0003923,CUST000682,Diya Reddy,Regular,SELL0328,Nagpur,Processing,27193.68,Pending - Breached,25.0,1.0,1.0,0.0,3.0,11,High,Order stuck past promised date; Refund failed; Refund exceeds order amount; Escalated ...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
4979,ORD0004980,CUST000403,Reyansh Patel,Premium,SELL0137,Hyderabad,Returned,42521.33,Severe,6.0,3.0,2.0,0.0,0.0,11,High,Severe delivery delay; Refund failed; Open refund past SLA; Refund exceeds order amoun...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
427,ORD0000428,CUST000637,Ira Rao,Plus,SELL0958,Delhi,Processing,15707.27,Pending - Breached,34.0,1.0,0.0,1.0,0.0,11,High,Order stuck past promised date; Open refund past SLA; Refund exceeds order amount; Neg...,Refund Ops: release pending refund (SLA breached),Refund Ops,2026-10-16 10:15:49

,order_id,customer_id,customer_name,customer_segment,seller_id,delivery_city,order_status,order_amount,delay_bucket,delivery_delay_days,refund_count,refund_failed,complaint_count,ticket_count,issue_score,issue_priority,priority_reasons,recommended_action,action_owner,report_generated_at
4300,ORD0004301,CUST000490,Anika Chopra,Premium,SELL0189,Bengaluru,Delivered,62080.09,On Time,-1.0,4.0,1.0,2.0,0.0,13,High,Refund failed; Open refund past SLA; Refund exceeds order amount; Negative complaint; ...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
2686,ORD0002687,CUST000018,Diya Singh,Regular,SELL0553,Kochi,Processing,23047.07,Pending - Breached,51.0,2.0,0.0,2.0,1.0,13,High,Order stuck past promised date; Open refund past SLA; Angry customer; Repeated complai...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
3695,ORD0003696,CUST000395,Ananya Verma,Regular,SELL0307,Chennai,Processing,59530.80,Pending - Breached,12.0,3.0,1.0,0.0,1.0,13,High,Order stuck past promised date; Refund failed; Open refund past SLA; Refund exceeds or...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
749,ORD0000750,CUST000431,Sai Khan,Regular,SELL0567,Mumbai,Delayed,40173.12,Severe,9.0,2.0,1.0,2.0,1.0,12,High,Severe delivery delay; Refund failed; Open refund past SLA; Negative complaint; Repeat...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
421,ORD0000422,CUST000756,Vivaan Ghosh,Business,SELL0957,Mumbai,Processing,46937.94,Pending - Breached,15.0,2.0,0.0,0.0,1.0,12,High,Order stuck past promised date; Open refund past SLA; Refund exceeds order amount; Esc...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49

## Section 19: Final Validation Checks

**Developer handover note:** Complete this section as the Python Developer responsible for repairing the inherited internal tool.

**Datasets to use:**
- `final_report`
- `debug_log`
- `notebook outputs`

**How to approach:**
- Check report file exists.
- Check required columns.
- Check priorities/actions/prompts are non-null.
- Check debug log evidence exists.

**Expected output format:**
- final_validation_df with check, passed, details.
- Final success message.

**Hint:**
- Validation output is the final engineering proof before handover.

In [23]:
# SECTION 19 — Final validation checks
# BROKEN/TODO: Add final checks that prove the product is complete.

report = pd.read_csv(REPORT_FILE)

final_validation_df = pd.DataFrame([
    {"check": "Report file exists", "passed": Path(REPORT_FILE).exists(), "details": REPORT_FILE},
    {"check": "Row count equals orders", "passed": len(report) == len(orders_df), "details": f"{len(report)} vs {len(orders_df)}"},
    {"check": "Required columns present", "passed": all(col in report.columns for col in report_columns), "details": f"{report.shape[1]} columns"},
    {"check": "No missing priority", "passed": report["issue_priority"].notna().all(), "details": report["issue_priority"].value_counts().to_dict()},
    {"check": "No missing action", "passed": report["recommended_action"].notna().all(), "details": ""},
    {"check": "No missing AI prompt", "passed": final_feature_table["ai_prompt"].notna().all(), "details": ""},
    {"check": "Debug log filled", "passed": len(debug_log) >= 10, "details": f"{len(debug_log)} entries"},
])
display(final_validation_df)
print("All checks passed. Project ready!" if final_validation_df["passed"].all() else "Some checks failed.")

log_fix("Section 19", "Validation not implemented", "Checks on report file, columns, nulls, debug log", f"{final_validation_df['passed'].sum()}/{len(final_validation_df)} passed")



# TODO:
# - check final report exists
# - check required columns
# - check no missing priorities
# - check notebook-visible outputs
print("Final validation not implemented yet.")

                      check  passed                                     details
0        Report file exists    True           final_issue_resolution_report.csv
1   Row count equals orders    True                                5000 vs 5000
2  Required columns present    True                                  20 columns
3       No missing priority    True  {'Low': 3698, 'Medium': 1180, 'High': 122}
4         No missing action    True
5      No missing AI prompt    True
6          Debug log filled    True                                  17 entries

All checks passed. Project ready!
Final validation not implemented yet.

## Notebook-Based Deliverable Placeholders

Fill the following sections inside this same notebook. Do not submit these as separate files.

In [24]:
# DELIVERABLE PLACEHOLDER — Debug Fix Log
# Fill this inside the notebook as you repair the inherited codebase.
debug_fix_log = pd.DataFrame(debug_log, columns=["section", "issue_found", "fix_applied", "validation_output"])
with pd.option_context("display.max_colwidth", None):
    display(debug_fix_log)

,section,issue_found,fix_applied,validation_output
0,Section 3,Code used non-existent column 'status',Used order_status and added full summary,7 status labels
1,Section 5,"Wrong file names/formats, 3 files not loaded","Correct reader for CSV, Excel, JSON, TXT",7 datasets loaded
2,Section 6,"Wrong column names, no relationship/date/amount checks",Added 12 checks + review table,"{'REVIEW': 10, 'PASS': 2}"
3,Section 7,"Only order_status lowercased; dates, amounts, other files ignored",clean_text + clean_date for all datasets,"[{'column': 'order_status', 'unique_before': 28, 'unique_after': 7}, {'column': 'payment_method', 'unique_before': 19, 'unique_after': 5}, {'column': 'delivery_city', 'unique_before': 32, 'unique_after': 16}]"
4,Section 8,Non-existent delivered_date column; pending orders ignored,Used actual_delivery_date + pending vs REFERENCE_DATE + buckets,"{'On Time': 2232, 'Minor': 765, 'Severe': 583, 'Cancelled': 488, 'Pending - Breached': 437, 'Moderate': 401, 'Lost': 86, 'Unknown': 8}"
5,Section 9,"Refunds not loaded correctly, no business rules","Added age, SLA, failed, amount mismatch, priority flag",712
6,Section 10,Complaints not loaded; wrong column 'order',Grouped by order_id with negative/angry/open counts,1299 orders with complaints
7,Section 11,"Wrong column resolution_hours, no SLA/escalation logic","SLA = 48h, escalation flag, order-level aggregate",1287 orders with tickets
8,Section 11,"Wrong column resolution_hours, no SLA/escalation logic","SLA = 48h, escalation flag, order-level aggregate",1287 orders with tickets
9,Section 12,Only exact duplicate rows were checked,"Checked duplicate IDs, duplicate-looking orders, repeat complaints/tickets","[16, 0, 412, 197]"
10,Section 13,Raw merges multiply rows,"Aggregated refunds/complaints/tickets first, then merged","[{'orders_rows': 5000, 'final_rows': 5000, 'row_count_ok': True}]"
11,Section 13,Raw merges multiply rows,"Aggregated refunds/complaints/tickets first, then merged","[{'orders_rows': 5000, 'final_rows': 5000, 'row_count_ok': True}]"
12,Section 14,Priority used delay only,"Score from delay, refund, complaint, ticket, customer segment + reasons","{'High': 122, 'Medium': 1180, 'Low': 3698}"
13,Section 15,Generic 'Review order' action,Team-specific actions from business signals,"{'None': 2524, 'City Ops': 926, 'Refund Ops': 589, 'Escalation Desk': 455, 'Support Ops': 347, 'Seller Ops': 95, 'Logistics Ops': 64}"
14,Section 16,Placeholder prompt,Structured prompt from case facts (no API call),5000 prompts
15,Section 17,Widgets not connected to data,Dropdown + search box filter final_feature_table,"priority, city, order ID filters"
16,Section 18,"Report had only 2 columns, no export","Full schema + timestamp, saved CSV","(5000, 20)"
17,Section 19,Validation not implemented,"Checks on report file, columns, nulls, debug log",7/7 passed

## AI Prompt Usage Log

Document how AI helped you, if used. You must still validate and explain all final code and outputs yourself.

In [25]:
# DELIVERABLE PLACEHOLDER — AI Prompt Usage Log
# Document how you used AI support, if any. Do not include private/sensitive data.
ai_prompt_usage_log = pd.DataFrame([
    ("Complete notebook sections 1-19",
     "Project incomplete hai, sab sections ek ek karke complete karwao",
     "Python/Pandas code for each section",
     "Ran every section in Colab and compared outputs (5000 rows, priority counts) with expected values"),
    ("Make code shorter and simpler",
     "Code chhota aur padhne me aasan chahiye, extra mat likho",
     "Compact version of all sections",
     "Re-ran the full notebook from Section 1; final_validation_df checks passed"),
    ("Priority score and recommended actions",
     "Rules for priority (High/Medium/Low) and team-wise actions",
     "score_case() and recommend_action()",
     "Checked High/Medium/Low counts and the reasons shown for top cases"),
    ("Deliverable tables",
     "Fill the deliverable placeholder cells",
     "Log tables and notes",
     "Read each table and confirmed numbers match the notebook outputs"),
], columns=["task", "prompt_used", "ai_output_used", "human_validation_done"])
with pd.option_context("display.max_colwidth", None):
    display(ai_prompt_usage_log)

,task,prompt_used,ai_output_used,human_validation_done
0,Complete notebook sections 1-19,"Project incomplete hai, sab sections ek ek karke complete karwao",Python/Pandas code for each section,"Ran every section in Colab and compared outputs (5000 rows, priority counts) with expected values"
1,Make code shorter and simpler,"Code chhota aur padhne me aasan chahiye, extra mat likho",Compact version of all sections,Re-ran the full notebook from Section 1; final_validation_df checks passed
2,Priority score and recommended actions,Rules for priority (High/Medium/Low) and team-wise actions,score_case() and recommend_action(),Checked High/Medium/Low counts and the reasons shown for top cases
3,Deliverable tables,Fill the deliverable placeholder cells,Log tables and notes,Read each table and confirmed numbers match the notebook outputs

## PRD Completion Mapping

Map product requirements to notebook sections and evidence.

In [26]:
# DELIVERABLE PLACEHOLDER — PRD Completion Mapping
# Map each PRD requirement to notebook evidence.
prd_completion_mapping = pd.DataFrame([
    ("Load all datasets (CSV, Excel, JSON, TXT)", "Section 5", f"{len(all_data)} datasets loaded", "Complete"),
    ("Validate data, flag invalid records", "Section 6", f"{len(validation_summary)} checks, {len(review_items_df)} orders flagged for review", "Complete"),
    ("Clean statuses, dates and amounts", "Section 7", f"order_status labels {cleaning_summary.loc[0, 'unique_before']} -> {cleaning_summary.loc[0, 'unique_after']}", "Complete"),
    ("Detect delayed orders", "Section 8", f"{int((orders_clean['delivery_delay_days'] > 0).sum())} delayed orders", "Complete"),
    ("Find refund-priority cases", "Section 9", f"{int(refunds_df['refund_priority_candidate'].sum())} priority refunds", "Complete"),
    ("Summarise complaints", "Section 10", f"{len(complaints_order)} orders with complaints", "Complete"),
    ("Summarise support tickets", "Section 11", f"{len(tickets_order)} orders with tickets", "Complete"),
    ("Detect duplicate and repeat issues", "Section 12", f"{duplicate_summary.loc[0, 'count']} duplicate order IDs", "Complete"),
    ("Final table without row explosion", "Section 13", f"{len(final_feature_table)} rows (same as orders)", "Complete"),
    ("Priority classification", "Section 14", str(priority_summary["cases"].to_dict()), "Complete"),
    ("Recommended actions", "Section 15", f"{final_feature_table['action_owner'].nunique()} owner teams", "Complete"),
    ("AI-ready prompts (no API call)", "Section 16", f"{len(final_feature_table)} prompts", "Complete"),
    ("Search and filter GUI", "Section 17", "Priority, city and order ID filters", "Complete"),
    ("Final report export", "Section 18", f"{REPORT_FILE} {final_report.shape}", "Complete"),
    ("Final validation", "Section 19", f"{int(final_validation_df['passed'].sum())}/{len(final_validation_df)} checks passed", "Complete"),
], columns=["prd_requirement", "notebook_section", "evidence", "completion_status"])
with pd.option_context("display.max_colwidth", None):
    display(prd_completion_mapping)

                              prd_requirement notebook_section                                      evidence completion_status
0   Load all datasets (CSV, Excel, JSON, TXT)        Section 5                             7 datasets loaded          Complete
1         Validate data, flag invalid records        Section 6      12 checks, 124 orders flagged for review          Complete
2           Clean statuses, dates and amounts        Section 7                   order_status labels 28 -> 7          Complete
3                       Detect delayed orders        Section 8                           2186 delayed orders          Complete
4                  Find refund-priority cases        Section 9                          712 priority refunds          Complete
5                        Summarise complaints       Section 10                   1299 orders with complaints          Complete
6                   Summarise support tickets       Section 11                      1287 orders with tickets          Complete
7          Detect duplicate and repeat issues       Section 12                        16 duplicate order IDs          Complete
8           Final table without row explosion       Section 13                    5000 rows (same as orders)          Complete
9                     Priority classification       Section 14    {'High': 122, 'Medium': 1180, 'Low': 3698}          Complete
10                        Recommended actions       Section 15                                 7 owner teams          Complete
11             AI-ready prompts (no API call)       Section 16                                  5000 prompts          Complete
12                      Search and filter GUI       Section 17           Priority, city and order ID filters          Complete
13                        Final report export       Section 18  final_issue_resolution_report.csv (5000, 20)          Complete
14                           Final validation       Section 19                             7/7 checks passed          Complete

## Assumption and Limitation Log

Document assumptions, edge cases, and implementation limitations.

In [27]:
# DELIVERABLE PLACEHOLDER — Assumption and Limitation Log
assumption_limitation_log = pd.DataFrame([
    ("Assumption", f"REFERENCE_DATE = {REFERENCE_DATE.date()} (latest date in data, not today) to age pending orders, refunds",
     "Change REFERENCE_DATE in Section 7 to re-age everything"),
    ("Assumption", f"Ticket SLA = {TICKET_SLA_HOURS} hours, refund SLA = {REFUND_SLA_DAYS} days",
     "Constants in Section 1, change if PRD says otherwise"),
    ("Decision", f"{int(orders_clean['order_id'].duplicated().sum())} duplicate order IDs are kept and flagged, not deleted",
     "Listed in review_items_df for manual check"),
    ("Edge case", f"{int((orders_clean['delay_bucket'] == 'Unknown').sum())} orders have no usable promised date, so delay is 'Unknown'",
     "Shown separately in delay_summary"),
    ("Edge case", "Tickets with blank resolution time are not counted as SLA breach",
     "Count may be slightly lower than reality"),
    ("Limitation", "Refunds, complaints or tickets pointing to unknown order IDs cannot join to an order",
     "Flagged in validation_summary"),
    ("Limitation", "Priority score weights (High >= 8, Medium >= 4) are rule-based judgement, not statistical",
     "Reasons column explains each score"),
    ("Limitation", "Data is synthetic and no AI API is called; prompts are only text",
     "Prompts are not tested against a model"),
], columns=["type", "description", "mitigation"])
with pd.option_context("display.max_colwidth", None):
    display(assumption_limitation_log)

         type                                                                                  description                                               mitigation
0  Assumption  REFERENCE_DATE = 2026-06-29 (latest date in data, not today) to age pending orders, refunds  Change REFERENCE_DATE in Section 7 to re-age everything
1  Assumption                                                   Ticket SLA = 48 hours, refund SLA = 7 days     Constants in Section 1, change if PRD says otherwise
2    Decision                                     16 duplicate order IDs are kept and flagged, not deleted               Listed in review_items_df for manual check
3   Edge case                                 8 orders have no usable promised date, so delay is 'Unknown'                        Shown separately in delay_summary
4   Edge case                             Tickets with blank resolution time are not counted as SLA breach                 Count may be slightly lower than reality
5  Limitation         Refunds, complaints or tickets pointing to unknown order IDs cannot join to an order                            Flagged in validation_summary
6  Limitation    Priority score weights (High >= 8, Medium >= 4) are rule-based judgement, not statistical                       Reasons column explains each score
7  Limitation                             Data is synthetic and no AI API is called; prompts are only text                   Prompts are not tested against a model

## Final Report Preview Evidence

Show report file name, shape, schema, and high-priority preview.

In [28]:
# DELIVERABLE PLACEHOLDER — Final Report Preview Evidence
# Show your final report path, shape, schema, and top priority preview.
final_report_preview_evidence = {
    "report_file": REPORT_FILE,
    "shape": final_report.shape,
    "columns": list(final_report.columns),
    "priority_counts": final_report["issue_priority"].value_counts().to_dict(),
    "generated_at": final_report["report_generated_at"].iloc[0],
}
display(final_report.head(5))
final_report_preview_evidence

,order_id,customer_id,customer_name,customer_segment,seller_id,delivery_city,order_status,order_amount,delay_bucket,delivery_delay_days,refund_count,refund_failed,complaint_count,ticket_count,issue_score,issue_priority,priority_reasons,recommended_action,action_owner,report_generated_at
4300,ORD0004301,CUST000490,Anika Chopra,Premium,SELL0189,Bengaluru,Delivered,62080.09,On Time,-1.0,4.0,1.0,2.0,0.0,13,High,Refund failed; Open refund past SLA; Refund exceeds order amount; Negative complaint; ...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
2686,ORD0002687,CUST000018,Diya Singh,Regular,SELL0553,Kochi,Processing,23047.07,Pending - Breached,51.0,2.0,0.0,2.0,1.0,13,High,Order stuck past promised date; Open refund past SLA; Angry customer; Repeated complai...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
3695,ORD0003696,CUST000395,Ananya Verma,Regular,SELL0307,Chennai,Processing,59530.80,Pending - Breached,12.0,3.0,1.0,0.0,1.0,13,High,Order stuck past promised date; Refund failed; Open refund past SLA; Refund exceeds or...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49
749,ORD0000750,CUST000431,Sai Khan,Regular,SELL0567,Mumbai,Delayed,40173.12,Severe,9.0,2.0,1.0,2.0,1.0,12,High,Severe delivery delay; Refund failed; Open refund past SLA; Negative complaint; Repeat...,Refund Ops: re-initiate failed refund and confirm with customer,Refund Ops,2026-10-16 10:15:49
421,ORD0000422,CUST000756,Vivaan Ghosh,Business,SELL0957,Mumbai,Processing,46937.94,Pending - Breached,15.0,2.0,0.0,0.0,1.0,12,High,Order stuck past promised date; Open refund past SLA; Refund exceeds order amount; Esc...,Escalation Desk: call customer back using merged complaint + ticket view,Escalation Desk,2026-10-16 10:15:49

{'report_file': 'final_issue_resolution_report.csv',
 'shape': (5000, 20),
 'columns': ['order_id',
  'customer_id',
  'customer_name',
  'customer_segment',
  'seller_id',
  'delivery_city',
  'order_status',
  'order_amount',
  'delay_bucket',
  'delivery_delay_days',
  'refund_count',
  'refund_failed',
  'complaint_count',
  'ticket_count',
  'issue_score',
  'issue_priority',
  'priority_reasons',
  'recommended_action',
  'action_owner',
  'report_generated_at'],
 'priority_counts': {'Low': 3698, 'Medium': 1180, 'High': 122},
 'generated_at': '2026-10-16 10:15:49'}

## Final Product Walkthrough

Explain the completed internal tool as if handing it back to Product and Engineering.

In [29]:
# DELIVERABLE PLACEHOLDER — Final Product Walkthrough
# Write 5-8 bullet points explaining how the completed product works for support operations.
final_product_walkthrough = [
    f"Load: all 7 files (CSV, Excel, JSON, TXT) are loaded by one loader class ({len(orders_clean)} orders).",
    "Check and clean: invalid records are flagged, labels, dates and amounts are standardised.",
    "Detect: delivery delay buckets, refund SLA/failed flags, complaint and ticket summaries per order.",
    f"Merge: everything is combined into one table of {len(final_feature_table)} rows (no duplicated rows).",
    f"Prioritise: score_case gives {priority_summary.loc['High', 'cases']} High, {priority_summary.loc['Medium', 'cases']} Medium, {priority_summary.loc['Low', 'cases']} Low cases with reasons.",
    "Act: each case gets a team-wise action and an AI-ready prompt; the filter widgets let a support lead explore cases.",
    f"Deliver: {REPORT_FILE} is exported and passes {len(final_validation_df)} validation checks.",
]
for point in final_product_walkthrough:
    print("-", point)

- Load: all 7 files (CSV, Excel, JSON, TXT) are loaded by one loader class (5000 orders).
- Check and clean: invalid records are flagged, labels, dates and amounts are standardised.
- Detect: delivery delay buckets, refund SLA/failed flags, complaint and ticket summaries per order.
- Merge: everything is combined into one table of 5000 rows (no duplicated rows).
- Prioritise: score_case gives 122 High, 1180 Medium, 3698 Low cases with reasons.
- Act: each case gets a team-wise action and an AI-ready prompt; the filter widgets let a support lead explore cases.
- Deliver: final_issue_resolution_report.csv is exported and passes 7 validation checks.

## Final Self-Check

Use this as your final readiness check before submission.

In [30]:
# DELIVERABLE PLACEHOLDER — Final Self-Check
final_self_check = pd.DataFrame([
    ("Dataset ZIP extracted and all sections run", "Done" if len(all_data) == 7 else "Check", f"{len(all_data)} datasets loaded"),
    ("Debug Fix Log filled", "Done" if len(debug_fix_log) > 0 else "Check", f"{len(debug_fix_log)} entries"),
    ("AI Prompt Usage Log filled", "Done" if len(ai_prompt_usage_log) > 0 else "Check", f"{len(ai_prompt_usage_log)} entries"),
    ("PRD Completion Mapping filled", "Done" if len(prd_completion_mapping) > 0 else "Check", f"{len(prd_completion_mapping)} requirements"),
    ("Assumption and Limitation Log filled", "Done" if len(assumption_limitation_log) > 0 else "Check", f"{len(assumption_limitation_log)} entries"),
    ("Final report exported and validated", "Done" if final_validation_df["passed"].all() else "Check", REPORT_FILE),
    ("Final Product Walkthrough written", "Done" if len(final_product_walkthrough) >= 5 else "Check", f"{len(final_product_walkthrough)} bullets"),
    ("No invalid record deleted", "Done" if len(orders_clean) == len(orders_df) else "Check", f"{len(orders_clean)} of {len(orders_df)} orders kept"),
], columns=["check_item", "status", "notes"])
display(final_self_check)

                                   check_item status                              notes
0  Dataset ZIP extracted and all sections run   Done                  7 datasets loaded
1                        Debug Fix Log filled   Done                         18 entries
2                  AI Prompt Usage Log filled   Done                          4 entries
3               PRD Completion Mapping filled   Done                    15 requirements
4        Assumption and Limitation Log filled   Done                          8 entries
5         Final report exported and validated   Done  final_issue_resolution_report.csv
6           Final Product Walkthrough written   Done                          7 bullets
7                   No invalid record deleted   Done           5000 of 5000 orders kept

## Presentation and Explanation Notes

Prepare a short explanation for reviewers/stakeholders.

In [31]:
# DELIVERABLE PLACEHOLDER — Presentation and Explanation Notes
top_city = city_delay_summary.index[0]
presentation_explanation_notes = f"""
PRESENTATION NOTES - {PROJECT_NAME}

1) Problem: support leads had no single view of risky orders. Data was in 7 files and the old notebook loaded only orders.csv.

2) What I built: load -> validate -> clean -> detect delay/refund/complaint/ticket issues -> merge -> priority score -> action -> report.

3) Key findings:
   - {len(orders_clean)} orders, {int((orders_clean['delivery_delay_days'] > 0).sum())} delayed; highest city delay rate: {top_city}.
   - {int(refunds_df['refund_priority_candidate'].sum())} of {len(refunds_df)} refunds need attention.
   - Priority: {priority_summary['cases'].to_dict()}.

4) Decisions I can explain:
   - Bad records are flagged, never deleted.
   - Refunds, complaints and tickets are grouped per order before merging, so rows do not multiply.
   - Priority uses delay, refund, complaint, ticket and customer signals; delay alone cannot make a case High.

5) Limitations: rule-based scores, assumed SLAs (48h tickets, 7 days refunds), 16 duplicate order IDs need manual check.
"""
print(presentation_explanation_notes)

PRESENTATION NOTES - Flipkart Order Issue Resolution Dashboard

1) Problem: support leads had no single view of risky orders. Data was in 7 files and the old notebook loaded only orders.csv.

2) What I built: load -> validate -> clean -> detect delay/refund/complaint/ticket issues -> merge -> priority score -> action -> report.

3) Key findings:
   - 5000 orders, 2186 delayed; highest city delay rate: Indore.
   - 712 of 1300 refunds need attention.
   - Priority: {'High': 122, 'Medium': 1180, 'Low': 3698}.

4) Decisions I can explain:
   - Bad records are flagged, never deleted.
   - Refunds, complaints and tickets are grouped per order before merging, so rows do not multiply.
   - Priority uses delay, refund, complaint, ticket and customer signals; delay alone cannot make a case High.

5) Limitations: rule-based scores, assumed SLAs (48h tickets, 7 days refunds), 16 duplicate order IDs need manual check.

## 100-Mark Evaluation Rubric

| Criteria | Marks |
|---|---:|
| Data loading and file handling for CSV, Excel, JSON, TXT, and ZIP extraction | 8 |
| Data validation and relationship quality checks | 10 |
| Data cleaning and standardization of statuses, dates, text, and amounts | 10 |
| Correct use of Python functions and modular code | 10 |
| OOP implementation and code organization | 8 |
| Core business logic for delays, refunds, complaints, tickets, and priority scoring | 12 |
| Pandas analysis and aggregations for operations insights | 10 |
| Colab GUI/search/filter experience | 8 |
| Report generation and notebook-visible outputs | 7 |
| Debug log, AI usage log, assumptions, and PRD mapping | 7 |
| Presentation & Explanation | 10 |
| **Total** | **100** |

## Final Submission Checklist

Before submitting the completed notebook, confirm:

- [x] Dataset ZIP was uploaded and extracted successfully.
- [x] All code cells run from top to bottom in Google Colab.
- [x] All major section outputs are visible.
- [x] Debug Fix Log is filled inside the notebook.
- [x] AI Prompt Usage Log is filled inside the notebook.
- [x] PRD Completion Mapping is filled inside the notebook.
- [x] Assumption and Limitation Log is filled inside the notebook.
- [x] Final Report Preview Evidence is visible.
- [x] Final Product Walkthrough is complete.
- [x] Final Self-Check is complete.
- [x] Presentation and Explanation Notes are complete.
- [x] The only final deliverable is the completed Colab notebook with all outputs visible.